# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 579ba682bbb36bdfce69d9ed64bafc48db1deb71c74cf177586e89ed024f87bed05f97589f538db57cf85ee5322b5e95e81a4bf26caed084853c02b7b4931de0

test:
  secret_key_base: ab02a88420722f2fb357fe3f7d34e30d30f090475ab1b75133f2586db184150763fc9e5994c213f4f191bc4c8565080d52d21c04cf04f494574fb9f6cabecd81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
